### ISSUE TITLE
assertion failed: max_rect.is_finite()

### ISSUE THREAD

**Issue by DonMartio** [Adanos020/egui_dock#140]
After the update to egui-0.22.0 and egui_dock-0.61.0 we get an assertion failure in egui/src/layout.rs[420].

After a little bit of digging i found this part in egui_dock/widgets/dock_area/mod.rs[415]:
```
 let tabbar_inner_rect = Rect::from_min_size(
                (tabbar_outer_rect.min - pos2(-*scroll, 0.0)).to_pos2(),
                vec2(f32::INFINITY, tabbar_outer_rect.height()),
);
```
I don't fully understand what should happen here, but my first suggestion would be to replace the 
```
                vec2(f32::INFINITY, tabbar_outer_rect.height()),
```
with
```
                vec2( tabbar_outer_rect.width(), tabbar_outer_rect.height()),
```
Although this may effect some scrolling behavior.

**To Reproduce**
Enable feature 'extra_debug_asserts'
```
egui = { version = "0.22.0", features = [
    "extra_debug_asserts"
] }
```

**Comment by Adanos020** [comment]
That's not good. I'll try what you're suggesting and see what happens.

**Comment by lvaroqui** [comment]
I tested the proposed fixed and it seems to work just fine since `max_rect` is a soft max and will allow UI to grow on overflow.

I got tricked by [this bit](https://github.com/emilk/egui/blob/5093b67e9b095072033e54557825f3bfc9d39c49/crates/egui/src/layout.rs#L29) in egui documentation...

I'll open a PR.
