### ISSUE TITLE
Scroll of DockArea

### ISSUE THREAD

**Issue by 12089897411** [Adanos020/egui_dock#148]
**Is your feature request related to a problem? Please describe.**

Yes, I'm getting frustrated when I use the 'scroll_area_in_tabs' method. This method only gives the scroll area for setting two-way scrolling, but cannot set horizontal scrolling and vertical scrolling separately.

**Describe the solution you'd like**

I hope that the method 'scroll_area_in_tabs' can include the function of setting one-way scrolling, or implement this function with a new method

**Comment by Adanos020** [comment]
Hey, that sounds like a good idea.

I'm a bit concerned that in widgets like `Window` disabling scrolling in one way will cause the window to resize to fit all of the contents in. Tabs on the other hand can't do that because the size of their bodies is always determined by positioning of splitters. That means any content that doesn't fit in the tab body will get clipped.

But maybe that isn't a problem. If this is the behaviour you're expecting then we can go ahead and give the users more control.

**Comment by Adanos020** [comment]
Closed by #160

On `release-0.7` you can now override `TabView::scroll_bars` to enable/disable individual scrollbars on individual tabs.
