### ISSUE TITLE
Tab Title Not Displayed When Surrounded by SidePanels

### ISSUE THREAD

**Issue by xiyuzhai** [Adanos020/egui_dock#190]
**Describe the bug**
If first create two side panels on the left and right, then create central panel and render tabs inside it, the title is not displayed.

**To Reproduce**
```
egui::SidePanel::left("explorer").show(ctx, |ui| ui.label("left"));
egui::SidePanel::right("assist_view").show(ctx, |ui| ui.label("right"));
egui::CentralPanel::default().show(ctx, |ui| self.tabs.ui(ui));
 ```

**Expected behavior**

**Screenshots**
https://github.com/xiyuzhai/egui-dock-bug/blob/main/egui_dock_bug.png

**Additional context**
See minimal code at
https://github.com/xiyuzhai/egui-dock-bug

**Comment by Adanos020** [comment]
In your simple reproduction, I noticed that the whole tab bar turns the mouse cursor to the pointing hand while hovered on. Even though no tabs are visually present, they are definitely there as they respond to user input: you can drag them out, close them, and create a split. If you put one of them to the right, this is what the result looks like this:

![image](https://github.com/Adanos020/egui_dock/assets/2311185/6886871f-e528-45ce-82ff-65305fc8574b)

I tried to reproduce this bug in the `simple` example by changing the implementation of `MyApp::update` to this:

```rs
fn update(&mut self, ctx: &egui::Context, _frame: &mut eframe::Frame) {
    egui::SidePanel::left("explorer").show(ctx, |ui| ui.label("left"));
    egui::SidePanel::right("assist_view").show(ctx, |ui| ui.label("right"));
    egui::CentralPanel::default().show(ctx, |ui| {
        DockArea::new(&mut self.tree)
            .style(Style::from_egui(ctx.style().as_ref()))
            .show(ctx, &mut TabViewer {});
    });
}
```

It doesn't behave the same way your reproduction does, the tab titles do show up normally.

![image](https://github.com/Adanos020/egui_dock/assets/2311185/ffe60c01-1f12-4db7-a55d-26e0f9c0d564)

I also observed that when you drag the right panel's border all the way to the left and then shrink it back, the tab titles do disappear.

![image](https://github.com/Adanos020/egui_dock/assets/2311185/87b75473-3f12-422a-b91c-0d7e7a89e00a)

The issue seems to be caused by something different than just surrounding the `CentralPanel` by two `SidePanel`s, possibly by the `CentralPanel` at some point having an area equal to 0. We shall dig more.

**Comment by Adanos020** [comment]
I identified the issue!

Basically, tab bars have a scrollbar whose position is based on a calculation which involves dividing something by the available width. When the available width for the `DockArea` is 0, the result of that division is NaN which immediately spreads into other areas within the `tabs_ui`, corrupting the whole tab bar.

I'm working on a fix right now.

**Comment by Adanos020** [comment]
I verified that the fix worked on the repro case you provided. Thank you for reporting this!
