### ISSUE TITLE
Add a way to iterate over surfaces

### ISSUE THREAD

**Issue by juh9870** [Adanos020/egui_dock#194]
**Is your feature request related to a problem? Please describe.**
Currently, it's only possible to get the main surface directly, and all others can only be fetched via ID

**Describe the solution you'd like**
Some method to get an iterator over active surfaces (including mut version)

Iterator over surface IDs would be great too

**Describe alternatives you've considered**
Using `iter_nodes` to get a list of all nodes, then use `find_node` on each of them and collect surface IDs into a unique set, then fetching surfaces via those IDs. Does this sound sane to you? I hope not

**Comment by Adanos020** [comment]
Yep, I think adding `iter_surfaces` and `iter_surface_ids` would be the best approach. For consistency it would be nice to also add `iter_node_ids` and `iter_tab_ids`. Furthermore, since there is a `iter_main_surface_nodes` and `iter_nodes`, I feel like we also need a `iter_surface_nodes` that lets you pick which surface's nodes you want.

I hope this makes sense, otherwise I appreciate other people's input!

**Comment by Adanos020** [comment]
Closed by #196

Also, I added `DockState::surfaces_count` which you can use to iterate over surface IDs using a range as such: `0..state.surfaces_count()`.
