### ISSUE TITLE
Sometimes vertical or horizontal resizing doesn't work.

### ISSUE THREAD

**Issue by Jerrody** [Adanos020/egui_dock#3]
We can see it even in an example `hello` of dragging separate tabs to the left side.

**Comment by Adanos020** [comment]
While fiddling with this a little I noticed this happens consistently when you move tabs between different nodes but not when you just split the tabs within the same parent node.

In other words: in the "hello" example take the "Scene" tab and put it to the right of "Node Tree". Since their original parent node is the same node that's now the parent of the new 2 nodes, resizing is possible. Same would happen if you put these tabs in the vertical orientation. Now move the "Scene" tab to the right of  "File Browser" and "Asset Manager" and now resizing doesn't work between them.

**Comment by Jerrody** [comment]
> While fiddling with this a little I noticed this happens consistently when you move tabs between different nodes but not when you just split the tabs within the same parent node.
> 
> In other words: in the "hello" example take the "Scene" tab and put it to the right of "Node Tree". Since their original parent node is the same node that's now the parent of the new 2 nodes, resizing is possible. Same would happen if you put these tabs in the vertical orientation. Now move the "Scene" tab to the right of "File Browser" and "Asset Manager" and now resizing doesn't work between them.

Yeah, I see the problem. I looked at the code, but I didn't see what causes it.

**Comment by Adanos020** [comment]
Looks like the debugger in CLion is going to come in handy. I'll take a look at this tomorrow.

**Comment by Jerrody** [comment]
> Looks like the debugger in CLion is going to come in handy. I'll take a look at this tomorrow.

I so many write in Rust, so I forgot how to debug XD

**Comment by Adanos020** [comment]
I did some more testing and found another weird behaviour:

1. In the `hello` example drag and drop the Asset Manager node next to File Browser in any direction: resizing between them doesn't work.
2. Now drag the Node Tree next to Scene (again, any direction). Resizing works between them, and now also between File Browser and Asset Manager.
3. Put Scene and Node Tree back together and now File Browser and Asset Manager can't be resized.

Resizing between Scene and Node Tree works regardless of the setup in any other nodes.

**Comment by Jerrody** [comment]
> I did some more testing and found another weird behaviour:
> 
> 1. In the `hello` example drag and drop the Asset Manager node next to File Browser in any direction: resizing between them doesn't work.
> 2. Now drag the Node Tree next to Scene (again, any direction). Resizing works between them, and now also between File Browser and Asset Manager.
> 3. Put Scene and Node Tree back together and now File Browser and Asset Manager can't be resized.
> 
> Resizing between Scene and Node Tree works regardless of the setup in any other nodes.

The problem can be in that exist two different Nodes: Vertical and Horizontal. When we change the tab and making it an individual Node (Vertical or Horizontal) this Leaf (in the past state) doesn't change to Horizontal or Vertical.

**Comment by Adanos020** [comment]
> I think that the problem can be in that exist two different Nodes: Vertical and Horizontal. When we change the tab and make it an individual Node (Vertical or Horizontal) this Leaf (in the past state) doesn't change to Horizontal or Vertical.

Just checked, this is not true (anymore?)

**Comment by Jerrody** [comment]
> > I think that the problem can be in that exist two different Nodes: Vertical and Horizontal. When we change the tab and make it an individual Node (Vertical or Horizontal) this Leaf (in the past state) doesn't change to Horizontal or Vertical.
> 
> Just checked, this is not true (anymore?)

This is 20d comment, so I think yes :)

**Comment by Adanos020** [comment]
The problem is still there though, so even if this was the case, the cause is different

**Comment by Adanos020** [comment]
I fixed this, but I have no idea why the thing I changed caused the bug. Let me explain.

Basically, I noticed that this bug happens very consistently in cases, when the binary tree is unbalanced and it never does if the tree _is_ balanced, even though the algorithm didn't recursively traverse the tree, it just iterated over the array of nodes from start to end.

So I looked at the array representations of a few trees, faulty and okay ones, and I noticed that in balanced trees all parent nodes are clumped together at the start of the array, and leaf nodes sit in another clump right after them. On the other hand, in unbalanced trees this harmony didn't exist at all, leaves and parents were interspersed with each other, and some groups were even split by clumps of empty nodes.

So I looked at this and was like "what if we always processed only the parents first, and then only the leaves?". I tried it... and it worked???

Still, no idea why it made any difference since the code for all nodes was always being executed, including drawing and input handling of the node separators. Honestly, I won't be surprised if the actual thing that breaks this causes other issues in the future.

**Comment by Jerrody** [comment]
> I fixed this, but I have no idea why the thing I changed caused the bug. Let me explain.
> 
> Basically, I noticed that this bug happens very consistently in cases, when the binary tree is unbalanced and it never does if the tree _is_ balanced, even though the algorithm didn't recursively traverse the tree, it just iterated over the array of nodes from start to end.
> 
> So I looked at the array representations of a few trees, faulty and okay ones, and I noticed that in balanced trees all parent nodes are clumped together at the start of the array, and leaf nodes sit in another clump right after them. On the other hand, in unbalanced trees this harmony didn't exist at all, leaves and parents were interspersed with each other, and some groups were even split by clumps of empty nodes.
> 
> So I looked at this and was like "what if we always processed only the parents first, and then only the leaves?". I tried it... and it worked???
> 
> Still, no idea why it made any difference since the code for all nodes was always being executed, including drawing and input handling of the node separators. Honestly, I won't be surprised if the actual thing that breaks this causes other issues in the future.


Yeah, I dunno, but that's so dumb bug. 

Anyway, I think that after your refactoring we should implement window creating by tab dragging. I opened a PR (draft) where I created small amount of work and I need help at this, because programming UI is not my territory.

I will refactor code of my PR to make understandable my code or **remake** it fully, because I think that my implementation is not the right thing.

After implementing this feature I guess to totally refactor project, because this is very huge code that very bad organized.

**Comment by Adanos020** [comment]
I think we should instead publish 0.2 now, and then actually start refactoring and designing the creation of windows out of tabs which we'll publish in 0.3. There are a couple of reasons for this.

First, 0.1 is very broken and limited (barely even usable if I'm being honest) and we already made enough improvements and additions to the library to make it significantly more usable.

Second, detaching and re-attaching tabs is going to be a bit complicated and require some thought about what we want to achieve with this, which means people would need to wait much longer for 0.2 with all fixes and additions. I'll enable a discussion board where we can chat about this feature.

**Comment by Jerrody** [comment]
> I think we should instead publish 0.2 now, and then actually start refactoring and designing the creation of windows out of tabs which we'll publish in 0.3. There are a couple of reasons for this.
> 
> First, 0.1 is very broken and limited (barely even usable if I'm being honest) and we already made enough improvements and additions to the library to make it significantly more usable.
> 
> Second, detaching and re-attaching tabs is going to be a bit complicated and require some thought about what we want to achieve with this, which means people would need to wait much longer for 0.2 with all fixes and additions. I'll enable a discussion board where we can chat about this feature.

Sounds logical. Alright, I think that this is a good idea to publish `0.2.`
