### ISSUE TITLE
`is_pointer_over_area` is false over DockArea

### ISSUE THREAD

**Issue by Aceeri** [Adanos020/egui_dock#95]
**Describe the bug**
Egui doesn't seem to recognize that the egui dock background is there and will return `is_pointer_over_area` as false.

**To Reproduce**
- Run the `repro.rs` example that is derived from the `simple.rs` example from here: https://github.com/Aceeri/egui_dock/blob/main/examples/repro.rs

**Screenshots**
https://user-images.githubusercontent.com/5142292/216484419-98152000-1c66-41e2-9757-9ee45e2a76de.mp4

**Additional context**
This is an issue with stuff like bevy_mod_picking and possibly others where they expect this method to reliably return that they are in an egui area.

**Comment by lvaroqui** [comment]
I did some investigation and I think I understand the problem.

To determine if the cursor is currently over egui for the background layer ([used by DockArea::show()](https://github.com/Adanos020/egui_dock/blob/main/src/lib.rs)), the `is_pointer_over_area()` function uses the internal egui state `unused_rect` (see [here](https://github.com/emilk/egui/blob/0.20.1/crates/egui/src/context.rs)). For the `CentralPanel`, this area is reduced to nothing in the `allocate_central_panel()` function ([here](https://github.com/emilk/egui/blob/0.20.1/crates/egui/src/containers/panel.rs) and [here](https://github.com/emilk/egui/blob/0.20.1/crates/egui/src/frame_state.rs)). However, in `DockArea::show` we cannot call this function, the best solution I think is to make the function create a `CentralPanel`, I'll share this in a PR.

Additional Note: the `is_pointer_over_area` function cannot be called reliably from inside panels since the panel updates the available_area after calling its `add_contents` function and there is no memory used to check the state in the previous frame. This might be a bug for egui itself.

**Comment by Adanos020** [comment]
Fixed partially by #98, whatever is left needs to be fixed in egui.
